import turtle

turtle.shape('turtle')
turtle.goto(0, 0)
turtle.fillcolor('yellow')
turtle.begin_fill()
turtle.circle(60)
turtle.end_fill()
turtle.penup()
turtle.goto(20, 70)
turtle.pendown()
turtle.fillcolor('blue')
turtle.begin_fill()
turtle.circle(10)
turtle.end_fill()
turtle.penup()
turtle.goto(-20, 70)
turtle.pendown()
turtle.fillcolor('blue')
turtle.begin_fill()
turtle.circle(10)
turtle.end_fill()
turtle.penup()
turtle.home()
turtle.goto(0, 60)
turtle.pendown()
turtle.pencolor('black')
turtle.pensize(8)
turtle.right(90)
turtle.forward(20)
turtle.penup()
turtle.goto(-20, 40)
turtle.pendown()
turtle.pencolor('red')
turtle.circle(20, 180, 100)



